### ISSUE TITLE
System.Drawing.Color conflict

### ISSUE THREAD

**Issue by grandchamp** [matgr1/System.Drawing-dotnet-core#1]
Hi.
I'm using ```SetPixel``` and i'm getting a exception ```The type 'Color' exists in both 'System.Drawing-dotnet-core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' and 'System.Drawing.Primitives, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	```
Maybe you should exclude it too from the code.

**Comment by grandchamp** [comment]
Investigating a little bit more, System.Drawing.Color is available only in netcoreapp2.0 package, maybe it'll be included in netstandard2.0.

**Comment by grandchamp** [comment]
Any updates on this? @matgr1 
This is blocking for who is using .NET Core 2.

**Comment by matgr1** [comment]
sorry, forgot about this!

I'll try to take a look soon, I did recently discover a workaround that might work depending on your situation: https://github.com/NuGet/Home/issues/4989#issuecomment-310565840

so in my .csproj I have: 

```csproj
  <Target Name="ChangeAliasesOfSystemDrawing" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
	<ItemGroup>
	  <ReferencePath Condition="'%(FileName)' == 'System.Drawing-dotnet-core'">
		<Aliases>SystemDrawing</Aliases>
	  </ReferencePath>
	</ItemGroup>
  </Target>
```

and where I need to use the interfaces from this package I have:

```cs
extern alias SystemDrawing;
using SystemDrawing::System.Drawing;
using SystemDrawing::System.Drawing.Imaging;
```

you could also do something like  this if you want to just grab the Color struct

```cs
extern alias SystemDrawing;
using SystemDrawingColor = SystemDrawing::System.Drawing.Color;
```

**Comment by grandchamp** [comment]
That's cool.
But i think it'll not work, because this implementation uses the same namespace, so, on this way, it'll get the same namespace for both files (System.Drawing.Primitives.dll and System.Drawing-dotnet-core.dll).
I've submitted an PR on both repos #2

**Comment by matgr1** [comment]
did you try the alias? It let's you handle these namespace conflicts by allowing you to explicitly tell the compiler which package to use for a given source file.

It may help if you end up referencing a package that uses CoreCompat for example (that's where I needed it, since they have their own definitions for some of these interfaces).

Either way, thanks for the PRs! they are merged and the new releases should be available on nuget

**Comment by malcolmjerry** [comment]
ReferencePath Condition="'%(FileName)' == 'CoreCompat.System.Drawing'">
